### ISSUE TITLE
Template does not include CNAME functions

### ISSUE THREAD

**Issue by NeilHanlon** [theforeman/smart_proxy_dns_plugin_template#3]
See https://github.com/theforeman/smart-proxy/pull/436

**Comment by ekohl** [comment]
I hope to get https://github.com/theforeman/smart-proxy/pull/492 merged and avoid the need for it altogether.

**Comment by NeilHanlon** [comment]
@ekohl Can this be closed, then?

**Comment by NeilHanlon** [comment]
And more importantly, what does this mean for this template?

**Comment by ekohl** [comment]
@NeilHanlon thanks for reminding me. The PR in smart-proxy is merged I can pick up https://github.com/theforeman/smart_proxy_dns_plugin_template/pull/5 now.

**Comment by ekohl** [comment]
Now that #5 is merged I'm going to close this. Feel free to re-open if anything is unclear.
